### ISSUE TITLE
fileIdx for stream with series

### ISSUE THREAD

**Issue by postnikovmaksim** [Stremio/stremio-addon-sdk#113]
I did not find a working way to determine the file number in the stream, having only infohash.

Is it possible to expand this setting and for example allow to specify the file name? This is true, for example, if the files are arranged in folders (by season)

**Comment by jaruba** [comment]
The file list of a torrent is stored in the torrent file. If you have a magnet link, then that will need to be used to get the torrent file from the swarm in order to get the torrent file (and thus the file list).

The file list has all the files listed in an exact order. The first file being `fileIdx: 0`.

There is also some torrent helpers deployed that can help simplify torrent related logic:


- Convert magnet links to torrent files: `https://torrent-helper.now.sh/magnet2torrent/?magnet=` followed by the URL encoded magnet link ([see server code](https://glitch.com/edit/#!/snow-napkin?path=server.js))

- Get file list from magnet links: `https://torrent-helper.now.sh/magnet2files/?magnet=` followed by the URL encoded magnet link ([see server code](https://glitch.com/edit/#!/ninth-trust?path=server.js))

**Comment by postnikovmaksim** [comment]
Thanks! Great way, not as fast as I would like, but it suits me.
Would recommend adding such a tip to the documentation

**Comment by jaruba** [comment]
That API died, there are some backups at:
- `https://bundle-helpers.now.sh/2files/?magnet=`
- `https://bundle-helpers.now.sh/2torrent/?magnet=`
