### ISSUE TITLE
Update documentation regarding expected catalog handler response type

### ISSUE THREAD

**Issue by doingodswork** [Stremio/stremio-addon-sdk#128]
I'm currently working on a generic Stremio addon SDK for Go and I'm trying to provide as many specific types as possible (instead of asking the SDK user to return a byte array as response or so). So I was trying to find out how the type for the catalog handler should be defined, but it's not clear to me.

The current documentation says for the `defineCatalogHandler` that an array of `Meta Preview Object`s is returned. Source: https://github.com/Stremio/stremio-addon-sdk/blob/0286edd80bda94cfda3120d7e9674fd907471e62/docs/api/requests/defineCatalogHandler.md#returns

The `Meta Preview Object` documentation also says explicitly that it's meant to be used for catalog responses:
> Used as a response for defineCatalogHandler

Source: https://github.com/Stremio/stremio-addon-sdk/blob/0286edd80bda94cfda3120d7e9674fd907471e62/docs/api/responses/meta.md#meta-preview-object

But it's lacking fields like genre, IMDb rating, year, director, actors and description, which the Stremio desktop app shows in the right sidebar when these fields are part of the response, without making another request to a meta endpoint if I'm not mistaken.

Then the `resources` page on the other hand says the response is `meta` and links to the full Meta objects. Source: https://github.com/Stremio/stremio-addon-sdk/tree/0286edd80bda94cfda3120d7e9674fd907471e62/docs/api#resources

Neither of the two descriptions contain a `year` field though, which is used in the code example for the catalog handler. Source: https://github.com/Stremio/stremio-addon-sdk/blob/0286edd80bda94cfda3120d7e9674fd907471e62/docs/api/requests/defineCatalogHandler.md#basic-example

`year` is also part of the response when looking at Cinemata responses.

=> I'm confused what exactly Stremio expects now, and what fields it can handle and which it can't.

If I'm mixing something up or overlooking some existing doc, please let me now. Otherwise it would be great if the documentation could be streamlined according to what Stremio actually expects (_requires_) and also _optionally_ uses for displaying a catalog item.

**Comment by Ivshti** [comment]
I think most of the fields that are currently not documented are actually obsolete and we intend to replace them with different ones.

`year` and `description` are perhaps simply missed, not intended to be obsoleted

@jaruba can you take a look?

**Comment by jaruba** [comment]
@doingodswork Sorry, i'm not sure how I missed the email notification for this issue.

So to clear up the confusion, `Meta Preview` and `Meta` are essentially the same object type, yet Catalogs, in general, only require an id, type, name and poster to show these items in Board, Discover, Search and Library.

It is true, though, that if other parameters such as: genres, releaseInfo, director, cast, imdbRating, description and trailers are set, then those would be used for the sidebar in Discover catalogs, but this is the only place where this info is used, and it indeed was missed in the docs.

The reason why `Meta` and `Meta Preview` are considered different, although they are the same object type, is because of the difference in their **required** parameters. As `Meta` does not require a `poster`, but `Meta Preview` does.

As for why the `Catalog` has `Meta` linked as the response on the resources page, well, both `Meta` and `Meta Preview` are described on the same page, as they are essentially the same object type.

You also asked about the `year` property from `Meta` objects, Cinemeta does indeed use this property, but we have marked this property as being deprecated, as it was replaced by `releaseInfo`. Cinemeta does use some older properties though, and Stremio is fully backward compatible with the old properties and even the old sdk.

I will try to update the docs to make things clearer though, and add the missing properties to `Meta Preview`.

Don't hesitate to ask if you have further questions, and thank you for turning my attention to this.

**Comment by jaruba** [comment]
I've created a PR for this: https://github.com/Stremio/stremio-addon-sdk/pull/129

**Comment by doingodswork** [comment]
Awesome! Thanks for taking care of this! Your comment already makes things clearer and the PR is great!

**Comment by doingodswork** [comment]
Closing the issue as it has been resolved. Thanks a lot!
