### ISSUE TITLE
Add 'headers' field to subtitle response object.

### ISSUE THREAD

**Issue by maormagori** [Stremio/stremio-addon-sdk#138]
Hello!
I'm currently working on a subtitle add-on for a site which requires logging in to download the subtitles. Calls to the download link without the login cookie return 401.
The workaround is to respond with a `url` that redirects back to the addon, make the call with the headers and send back the data.

This can be avoided with a `headers` field that will contain an array of key-value objects that will be the headers for the subtitles url. I believe you already implement it in another response but couldn't find it.

**Comment by Ivshti** [comment]
Unfortunately this is quite difficult to implement since on some platforms (eg web) not all headers can be controlled due to CORS restrictions. So even if we implement it, it won't be consistent across platforms and it might lead to hard to replicate bugs

It's best we keep this out of the addon protocol and rely on addons proxying the calls
