### ISSUE TITLE
Is that possible to work on RPi

### ISSUE THREAD

**Issue by fabianmendes** [Stremio/stremio-addon-sdk#150]
How can I make it work on a Raspberry Pi (armhf and/or arm64/aarch64)? Thanks

**Comment by jaruba** [comment]
I'm confused regarding your question, how do you make the sdk work on RPI? If so, install node and follow the sdk docs.

Otherwise, how you make Stremio work on RPI? We do not officially support RPI, but a simple google search pulled up this community project: https://github.com/shivasiddharth/Stremio-RaspberryPi
