### ISSUE TITLE
Addon guide asks to name a file with ':' but it isn't possible. Can't upload TV episodes.

### ISSUE THREAD

**Issue by fedew04** [Stremio/stremio-addon-sdk#207]
In section 6 of the generic addon guide, there's a part where you need to put ':' in a file name, however, it's not possible on Windows.
![image](https://user-images.githubusercontent.com/65686048/208282548-61ae63f0-8038-424d-97b5-8caa2e4d04f1.png)
By the way, Stremio specifically asks for a ':' to be used in the name file: (%3A is ':' in HTML)
![image](https://user-images.githubusercontent.com/65686048/208282599-cbf2c46f-1772-4abf-a37e-05649916baba.png)
How can I fix this? Is it a bug?

**Comment by jaruba** [comment]
@fedew04 

No, this is not a bug, the docs are just suggesting to use colon (`:`), because the Cinemeta official addon uses it, colon is only an invalid character for filename on Windows.

The video ID comes from `meta.videos[].id` and it can be any string of your choosing, it does not need to include a colon at all.

**Comment by fedew04** [comment]
> @fedew04
> 
> No, this is not a bug, the docs are just suggesting to use colon (`:`), because the Cinemeta official addon uses it, colon is only an invalid character for filename on Windows.
> 
> The video ID comes from `meta.videos[].id` and it can be any string of your choosing, it does not need to include a colon at all.

thank you!
