### ISSUE TITLE
Add Addon notification panel

### ISSUE THREAD

**Issue by seddik88** [Stremio/stremio-addon-sdk#264]
Some add-ons change host, or update the addon with some critical change and the community has no way to know unless you follo the developers of each addon on reddit and or GitHub...

I propose a notification panel within Stremio where each addon can notify it's user of anything relevant..

You could add a tab in add-ons where it says notifications and developers can notify of changes and or updates

**Comment by jaruba** [comment]
the problem with this suggestion is that it can be heavily abused by addon developers, imagine getting ads in the form of notifications in Stremio.. the users will blame Stremio, not the addon developers, as many forget what addons they installed, and some even install all possible addons because "they want to have everything"

addons should handle content only, i really don't think that there should be a social aspect to them at all

i have seen developers abuse of the addon configuration page too (which we allowed to be a standard web page for flexibility reasons), i have even seen one configuration page that was an ad/spam festival by throwing pop-ups on each and every click..

User safety should be a priority, and imho such a change would go against that

**Comment by seddik88** [comment]
I don't know what to say to that, ideally I would like add-ons to be allowed to behave like Kodi's, auto update automatically... That would be the best and safer way

**Comment by jaruba** [comment]
Stremio addons can never behave like Kodi addons, because Stremio does not run the addons locally.

This means that all changes to an addon (except the addon manifest) are always updated. (with the exception of CDN cache if the addon uses one)

The addon manifest is currently only automatically updated if:
- the addon is published to the community list of addons (the one visible in the apps under "Community" on the Addons page)
- the addon was not configured by the user (configuring an addon creates a completely new addon manifest URL, so it is considered a different addon than the one published in the community addons list)

The reason why auto-updating the addon manifest can only be done in these circumstances is a technical limitation, we consider it an important task, and are looking into it, but there is no current ETA.

**Comment by seddik88** [comment]
I understand. Thanks for your answer... Isn't there a patch for the time being?like host an official centralized platform or forum for add-ons developers to communicate with users?

Create a space where all info is centralized. 

As a user I would like to know that if I go to ONE place I get all the info I need about updates or new developments

**Comment by jaruba** [comment]
> As a user I would like to know that if I go to ONE place I get all the info I need about updates or new developments

The official communities handle support for the Stremio apps only, not community built addons. Also, addon developers are under no obligation to be reachable, they can choose to work anonymously / privately and also choose to be unreachable.

There may be many unofficial communities though, it is likely that we don't know about all of them, but one such community can be found at: https://www.reddit.com/r/StremioAddons/

**Comment by Blockr22** [comment]
Having a notification panel would be nice, where devs can post important info. why not limit only 1 notification per 24hrs and also add a thumbs up and thumbs down to that notification aswell. As only notification is needed for community addons since those can't be auto updated unlike official addons. let community decide who already use that addon if that notification is usefull with thumbs up and thumbs down otherwise. if some developer misuse/abuse this feature with ads or something, community will automatically backlash and people will just uninstall that addon if the dev just keep getting thumbs down or block/delete that notification when particular percent people dislike it. The notification can strictly be used to rely info for how to update or not to.
