### ISSUE TITLE
Search not work if  catalogs genre "isRequired true"

### ISSUE THREAD

**Issue by ewwink** [Stremio/stremio-addon-sdk#266]
if I set genre with `"isRequired": true` my addon has no search function,  it is expected behavior? 
 
```
"catalogs": [{
    "id": "myaddon",
    "name": "test addon",
    "extra": [{
        "name": "search",
        "isRequired": false
      }
      {
        "name": "genre",
        "options": [
          "New Release",
          "Most Seeder"
        ],
        "isRequired": true // <= the problem
      }
    ]
  }
]
```

**Comment by dexter21767-dev** [comment]
yes that's by design.
you're setting the genre as a required option, which means this catalog will only appear in the discovery page (where u can select the genre), and since u can't select the genre in the search or in the board it won't appear there. 
if u want it to appear in all these u need to set it to false.

and if u set the search as required then it won't appear in discovery or board.

**Comment by ewwink** [comment]
OK I just need to add search only catalog and thanks.

**Comment by dexter21767-dev** [comment]
@ewwink you can have one catalog for everything if that's what u want, just make sure to set "isrequired" to false for everything.
