### ISSUE TITLE
Docs regarding types in Discover - Others, Anime, ??

### ISSUE THREAD

**Issue by EnArvy** [Stremio/stremio-addon-sdk#273]
I could not find anything in the docs regarding what goes in the select options besides Movies, Series, TV, Channels. Especially Anime, which I also see some addons listing as type in Catalog. Any help regarding this?

**Comment by jaruba** [comment]
`movie`, `series`, `tv` and `channel` are the only official catalogs (and meta) types

but for catalogs, we allow any custom string to be a valid catalog type, while `anime` is not an official type, it has been widely used by community developers

so the reason those are not documented is because they are not official, but still accepted (as any string is accepted for catalog types)

**Comment by EnArvy** [comment]
So is there extra support for "anime" to show on Discover page? What about "Others" ?

**Comment by jaruba** [comment]
i edited my comment as `other` is also an official type, although very rarely used today

`other` was made for all other cases that do not fit into `movie`, `series`, `tv` and `channel`, but it was made many years before we ever allowed custom types (any string) as an accepted value for catalogs in all Stremio apps

it is rarely used today specifically because we now allow custom types

**Comment by jaruba** [comment]
but you asked for "extra support for anime", i am not sure what ur question means, for catalogs, as stated, it can be any string, you can name the catalog type "heaven" or "hell" and it will be accepted, but the meta objects that respond to the catalog request can only use one of the official types listed above

**Comment by jaruba** [comment]
it should also be noted that catalogs can include metas of multiple types, so a catalog can respond with both movies, series, channels, etc

the catalog type does not presume that the metas in the catalog must have the same type as the catalog

**Comment by jaruba** [comment]
also to note, as far as i know, "anime" is not specific to movie or series, and more so, on anime metadata websites, the movie and series items are mixed within lists, not separated

and as mentioned above, you can mix these meta types in Stremio catalogs also (regardless of the catalog type, be it "anime" or anything else)

i hope this response is detailed enough

**Comment by EnArvy** [comment]
Thanks for the detailed response. What I meant by extra support is that it shows up in Discover tab whereas other random strings don't.
![Screenshot 2024-04-11 202803](https://github.com/Stremio/stremio-addon-sdk/assets/70991883/2c1df035-9b0c-4ec9-80c0-d8caf78d16c6)

**Comment by jaruba** [comment]
but this is not true, the types that u choose on the Discover page are dictated by `catalog.type`: https://github.com/Stremio/stremio-addon-sdk/blob/master/docs/api/responses/manifest.md#catalog-format

and it can be any string, the addon developer can make up anything that goes there, `anime` is not special at all, it is a custom type for catalogs that some addons use
