### ISSUE TITLE
Add ftp as video stream protocols supported

### ISSUE THREAD

**Issue by pitetb** [Stremio/stremio-addon-sdk#84]
Hello,

I'm thinking about developing an addon to allow user to search and watch videos from a private ftp repository. Currently, according to the documentation, only http, https and rtmp protocols are supported for a video stream.

Could it be possible to add the support of (s)ftp streams with this kind of format: 
ftp://user:pwd@server/videopath.mkv

If ftp is not possible what about webdav support?

Thank you for any response.

**Comment by Ivshti** [comment]
ftp is probably possibl,e but webdav is not; we'll consider ftp

@jaruba what do you think

**Comment by pitetb** [comment]
Thank you for your answer. Looking forward to see it!

**Comment by pitetb** [comment]
Hello! Any news regarding this feature?

**Comment by Ivshti** [comment]
Yes, we decided against that because of two things together

1) stremio wants to move to the browser ASAP
2) https://www.ghacks.net/2019/08/16/google-chrome-82-wont-support-ftp-anymore/

As a workaround you can develop a local addon (either from scratch or using PimpMyStremio) that proxies FTP streams.
